<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Product;
use App\Models\Category;
use App\Models\Unit;
use App\Models\Shop;

class ShopTypeFullCatalogueSeeder extends Seeder
{
    public function run(): void
    {
        $map = $this->fullCatalogue();

        $created = 0; $skipped = 0;
        foreach ($map as $shopTypeKey => $products) {
            $typeInfo = Shop::types()[$shopTypeKey] ?? null;
            if (!$typeInfo) continue;
            // Find a shop with this type for shop_id assignment, fallback to null (global)
            $shopForType = Shop::whereJsonContains('shop_type', $shopTypeKey)->first();
            $shopId = $shopForType?->id;
            if (!$shopForType) $shopId = null;

            foreach ($products as $p) {
                [$name, $categoryName, $unitName, $productType, $tax] = $p;
                if (Product::where('name', $name)->exists()) { $skipped++; continue; }

                $cat = Category::where('name', $categoryName)->first();
                if (!$cat) {
                    $cat = Category::firstOrCreate(['slug'=>Str::slug($categoryName)], ['name'=>$categoryName, 'description'=>'Auto from full catalogue', 'is_active'=>true, 'shop_types'=>[$shopTypeKey]]);
                } else if (empty($cat->shop_types) || !in_array($shopTypeKey, (array)$cat->shop_types)) {
                    $types = array_unique(array_merge($cat->shopTypesArray(), [$shopTypeKey]));
                    $cat->shop_types = $types;
                    $cat->save();
                }

                $unit = Unit::where('name', $unitName)->orWhere('short_name', strtolower($unitName))->first();
                if (!$unit) {
                    $unit = Unit::firstOrCreate(['name'=>$unitName], ['short_name'=>strtolower(substr($unitName,0,3)), 'is_active'=>true]);
                }

                $sku = strtoupper(Str::slug(substr($name,0,14), '-')).'-'.strtoupper(Str::random(3)).rand(10,99);
                $taxRate = str_contains((string)$tax, '18') ? 18 : 0;

                Product::create([
                    'shop_id' => $shopId,
                    'name' => $name,
                    'sku' => $sku,
                    'barcode' => null,
                    'category_id' => $cat->id,
                    'brand_id' => null,
                    'unit_id' => $unit->id,
                    'supplier_id' => null,
                    'buying_price' => 0,
                    'selling_price' => 0,
                    'wholesale_price' => null,
                    'current_stock' => 0,
                    'min_stock' => 5,
                    'tax_rate' => $taxRate,
                    'product_type' => $productType,
                    'track_stock' => $productType !== 'Service',
                    'track_batch' => false,
                    'track_expiry' => in_array($categoryName, ['Health & Pharmacy','Baby Care','Dairy','Bakery','Meat & Seafood','Fruits & Vegetables']),
                    'status' => 'active',
                    'is_sample' => true,
                    'description' => $name.' — Full sample for '.$typeInfo['label'],
                ]);
                $created++;
            }
        }

        $this->command->info("ShopType full catalogue: $created created, $skipped skipped. Total products: ".Product::count());
    }

    private function fullCatalogue(): array
    {
        // Each shop type => list of [Product Name, Category, Unit, Product Type, Tax]
        return [
            'general' => [
                ['Sugar Brown 2kg','Groceries','Kg','Physical','0'],
                ['Rice Basmati 5kg','Groceries','Bag','Physical','0'],
                ['Tea Bags 100s','Beverages','Box','Physical','18'],
                ['Instant Coffee 200g','Beverages','Jar','Physical','18'],
                ['Cooking Salt 1kg','Groceries','Packet','Physical','0'],
                ['Spaghetti 500g','Groceries','Packet','Physical','18'],
                ['Tomato Paste 400g','Groceries','Tin','Physical','18'],
                ['UHT Milk 500ml','Dairy','Bottle','Physical','0'],
                ['Butter Salted 250g','Dairy','Pack','Physical','0'],
                ['Cheese Cheddar 200g','Dairy','Pack','Physical','0'],
                ['Laundry Soap Bar','Household & Cleaning','Piece','Physical','18'],
                ['Liquid Soap 500ml','Household & Cleaning','Bottle','Physical','18'],
                ['Toilet Paper 6pk','Household & Cleaning','Pack','Physical','18'],
                ['Batteries AA 4pk','General Merchandise','Pack','Physical','18'],
                ['Matches Box','General Merchandise','Box','Physical','18'],
                ['Candles Pack','General Merchandise','Pack','Physical','18'],
                ['Soda 1L','Beverages','Bottle','Physical','18'],
                ['Juice Mango 1L','Beverages','Bottle','Physical','18'],
                ['Biscuits Cream 200g','Snacks & Confectionery','Packet','Physical','18'],
                ['Chocolate Bar','Snacks & Confectionery','Piece','Physical','18'],
            ],
            'mini_supermarket' => [
                ['Corn Flakes 500g','Groceries','Box','Physical','18'],
                ['Oats 1kg','Groceries','Packet','Physical','18'],
                ['Honey 500g','Groceries','Jar','Physical','18'],
                ['Jam Strawberry 500g','Groceries','Jar','Physical','18'],
                ['Peanut Butter Crunchy 500g','Groceries','Jar','Physical','18'],
                ['Mayonnaise Squeeze 500ml','Groceries','Bottle','Physical','18'],
                ['Ketchup 500ml','Groceries','Bottle','Physical','18'],
                ['Yoghurt Drinking 500ml','Dairy','Bottle','Physical','0'],
                ['Ice Cream Vanilla 1L','Frozen Foods','Tub','Physical','18'],
                ['Fish Fillet Frozen 1kg','Frozen Foods','Kg','Physical','18'],
                ['Chicken Wings Frozen 1kg','Frozen Foods','Kg','Physical','18'],
                ['Beef Burger Patties 500g','Frozen Foods','Pack','Physical','18'],
                ['Green Peas Frozen 500g','Frozen Foods','Packet','Physical','18'],
                ['Apple Red 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Banana Cavendish 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Orange 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Onion Red 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Shampoo Anti-Dandruff 400ml','Personal Care','Bottle','Physical','18'],
                ['Face Wash 100ml','Personal Care','Tube','Physical','18'],
                ['Baby Diapers Medium 20s','Baby Care','Pack','Variable','18'],
            ],
            'supermarket' => [
                ['Olive Oil 1L','Cooking Essentials','Bottle','Physical','18'],
                ['Sunflower Oil 5L','Cooking Essentials','Bottle','Physical','18'],
                ['Vinegar 500ml','Cooking Essentials','Bottle','Physical','18'],
                ['Black Pepper 50g','Cooking Essentials','Packet','Physical','18'],
                ['Curry Powder 100g','Cooking Essentials','Packet','Physical','18'],
                ['Frozen Pizza 400g','Frozen Foods','Box','Physical','18'],
                ['Fish Fingers 500g','Frozen Foods','Box','Physical','18'],
                ['Mozzarella 200g','Dairy','Pack','Physical','0'],
                ['Cream Cheese 200g','Dairy','Pack','Physical','0'],
                ['Cat Food Dry 1kg','General Merchandise','Bag','Physical','18'],
                ['Dog Food Wet 400g','General Merchandise','Tin','Physical','18'],
                ['Laundry Softener 1L','Household & Cleaning','Bottle','Physical','18'],
                ['Dish Sponge Pack','Household & Cleaning','Pack','Physical','18'],
                ['Aluminium Foil 30m','Household & Cleaning','Roll','Physical','18'],
                ['Cling Film 30m','Household & Cleaning','Roll','Physical','18'],
                ['Trash Bags 30L 20s','Household & Cleaning','Roll','Physical','18'],
                ['Air Freshener Spray','Household & Cleaning','Bottle','Physical','18'],
                ['Light Bulb LED 9W','General Merchandise','Piece','Physical','18'],
                ['Extension Cable 3m','General Merchandise','Piece','Physical','18'],
                ['Umbrella Compact','General Merchandise','Piece','Physical','18'],
            ],
            'pharmacy' => [
                ['Amoxicillin 500mg Capsules 20s','Health & Pharmacy','Box','Physical','0'],
                ['Azithromycin 500mg Tablets 3s','Health & Pharmacy','Box','Physical','0'],
                ['Metformin 500mg Tablets 30s','Health & Pharmacy','Box','Physical','0'],
                ['Losartan 50mg Tablets 30s','Health & Pharmacy','Box','Physical','0'],
                ['Atorvastatin 20mg Tablets 30s','Health & Pharmacy','Box','Physical','0'],
                ['Salbutamol Inhaler 100mcg','Health & Pharmacy','Piece','Physical','0'],
                ['Insulin Glargine Pen','Health & Pharmacy','Piece','Physical','0'],
                ['Oral Rehydration Salts Box 20s','Health & Pharmacy','Box','Physical','0'],
                ['Zinc Sulphate 20mg Tablets 10s','Health & Pharmacy','Pack','Physical','0'],
                ['Coartem 20/120 Tablets 24s','Health & Pharmacy','Box','Physical','0'],
                ['Albendazole 400mg Tablets 1s','Health & Pharmacy','Pack','Physical','0'],
                ['Mebendazole 500mg Tablets 1s','Health & Pharmacy','Pack','Physical','0'],
                ['Quinine Tablets 300mg 10s','Health & Pharmacy','Box','Physical','0'],
                ['Doxycycline 100mg Capsules 10s','Health & Pharmacy','Box','Physical','0'],
                ['Ciprofloxacin 500mg Tablets 10s','Health & Pharmacy','Box','Physical','0'],
                ['Fluconazole 150mg Capsules 2s','Health & Pharmacy','Pack','Physical','0'],
                ['Miconazole Cream 15g','Health & Pharmacy','Tube','Physical','0'],
                ['Clotrimazole Cream 20g','Health & Pharmacy','Tube','Physical','0'],
                ['Betamethasone Cream 15g','Health & Pharmacy','Tube','Physical','0'],
                ['Diclofenac Gel 20g','Health & Pharmacy','Tube','Physical','0'],
            ],
            'clothing' => [
                ['Men\'s Polo Shirt','Clothing & Apparel','Piece','Variable','18'],
                ['Men\'s Formal Shirt White','Clothing & Apparel','Piece','Variable','18'],
                ['Men\'s Chinos Khaki','Clothing & Apparel','Piece','Variable','18'],
                ['Men\'s Shorts Denim','Clothing & Apparel','Piece','Variable','18'],
                ['Women\'s T-Shirt Printed','Clothing & Apparel','Piece','Variable','18'],
                ['Women\'s Jeans Skinny','Clothing & Apparel','Piece','Variable','18'],
                ['Women\'s Office Skirt','Clothing & Apparel','Piece','Variable','18'],
                ['Women\'s Hijab Chiffon','Clothing & Apparel','Piece','Variable','18'],
                ['Children\'s School Shorts','Clothing & Apparel','Piece','Variable','18'],
                ['Children\'s Dress Floral','Clothing & Apparel','Piece','Variable','18'],
                ['Men\'s Leather Belt','Footwear','Piece','Variable','18'],
                ['Women\'s Handbag Leather','Clothing & Apparel','Piece','Variable','18'],
                ['Sneakers Running Unisex','Footwear','Pair','Variable','18'],
                ['Leather Formal Shoes Black','Footwear','Pair','Variable','18'],
                ['Sandals Leather Brown','Footwear','Pair','Variable','18'],
                ['School Shoes Black','Footwear','Pair','Variable','18'],
                ['Socks Cotton 3pk','Clothing & Apparel','Pack','Variable','18'],
                ['Cap Baseball','Clothing & Apparel','Piece','Variable','18'],
                ['Jacket Denim','Clothing & Apparel','Piece','Variable','18'],
                ['Kikoy Sarong','Clothing & Apparel','Piece','Variable','18'],
            ],
            'electronics' => [
                ['Smartphone 6.5" 64GB','Electronics','Piece','Physical','18'],
                ['Smartphone 6.7" 128GB','Electronics','Piece','Physical','18'],
                ['Feature Phone Dual SIM','Electronics','Piece','Physical','18'],
                ['Tablet 10" 32GB','Electronics','Piece','Physical','18'],
                ['LED TV 32"','Electronics','Piece','Physical','18'],
                ['LED TV 50" 4K','Electronics','Piece','Physical','18'],
                ['Soundbar 2.1','Electronics','Piece','Physical','18'],
                ['Bluetooth Earbuds Pro','Electronics','Pair','Physical','18'],
                ['Wired Earphones','Electronics','Pair','Physical','18'],
                ['Fast Charger 20W','Electronics','Piece','Physical','18'],
                ['Car Charger Dual','Electronics','Piece','Physical','18'],
                ['Power Bank 20000mAh','Electronics','Piece','Physical','18'],
                ['HDMI Cable 2m','Electronics','Piece','Physical','18'],
                ['USB-C Cable 1m','Electronics','Piece','Physical','18'],
                ['Memory Card 64GB','Electronics','Piece','Physical','18'],
                ['TV Wall Bracket 32-55"','Electronics','Piece','Physical','18'],
                ['Remote Universal','Electronics','Piece','Physical','18'],
                ['Extension Power Strip 4-way','Electronics','Piece','Physical','18'],
                ['LED Bulb Smart 9W','Electronics','Piece','Physical','18'],
                ['Solar Lantern','Electronics','Piece','Physical','18'],
            ],
            'computer' => [
                ['Laptop 14" i5 8GB/256GB','Electronics','Piece','Physical','18'],
                ['Laptop 15.6" i3 8GB/512GB','Electronics','Piece','Physical','18'],
                ['Gaming Laptop i7 RTX','Electronics','Piece','Physical','18'],
                ['Desktop i5 8GB 1TB','Electronics','Piece','Physical','18'],
                ['Monitor 24" FHD','Electronics','Piece','Physical','18'],
                ['Monitor 27" 4K','Electronics','Piece','Physical','18'],
                ['Mechanical Keyboard RGB','Electronics','Piece','Physical','18'],
                ['Wireless Mouse Ergonomic','Electronics','Piece','Physical','18'],
                ['Webcam 1080p','Electronics','Piece','Physical','18'],
                ['Headset Gaming 7.1','Electronics','Piece','Physical','18'],
                ['USB Hub 4-port','Electronics','Piece','Physical','18'],
                ['Flash Drive 64GB','Electronics','Piece','Physical','18'],
                ['External SSD 512GB','Electronics','Piece','Physical','18'],
                ['HDD External 1TB','Electronics','Piece','Physical','18'],
                ['RAM DDR4 8GB','Electronics','Piece','Physical','18'],
                ['Printer Laser Mono','Electronics','Piece','Physical','18'],
                ['Printer Inkjet Color','Electronics','Piece','Physical','18'],
                ['Scanner Flatbed A4','Electronics','Piece','Physical','18'],
                ['Barcode Scanner Handheld','Electronics','Piece','Physical','18'],
                ['POS Thermal Printer 80mm','Electronics','Piece','Physical','18'],
            ],
            'hardware' => [
                ['Cement 42.5N 50kg','Building Materials','Bag','Physical','18'],
                ['Sand Fine Ton','Building Materials','Cubic Metre','Physical','18'],
                ['Ballast 3/4 Ton','Building Materials','Cubic Metre','Physical','18'],
                ['Concrete Blocks 6"','Building Materials','Piece','Physical','18'],
                ['Steel Bar Y12 12m','Building Materials','Piece','Physical','18'],
                ['Binding Wire Roll 25kg','Building Materials','Roll','Physical','18'],
                ['Roof Sheet IT4 2.5m','Building Materials','Piece','Physical','18'],
                ['Nails 3" 1kg','Hardware & Tools','Kg','Physical','18'],
                ['Hammer Claw 16oz','Hardware & Tools','Piece','Physical','18'],
                ['Screwdriver Set 6pc','Hardware & Tools','Set','Physical','18'],
                ['Pliers Combination 8"','Hardware & Tools','Piece','Physical','18'],
                ['Wrench Set 12pc','Hardware & Tools','Set','Physical','18'],
                ['Drill Bits Set 19pc','Hardware & Tools','Set','Physical','18'],
                ['Measuring Tape 5m','Hardware & Tools','Piece','Physical','18'],
                ['Spirit Level 60cm','Hardware & Tools','Piece','Physical','18'],
                ['PVC Pipe 4" 3m','Hardware & Tools','Piece','Physical','18'],
                ['Elbow PVC 4"','Hardware & Tools','Piece','Physical','18'],
                ['Tap Mixer Chrome','Hardware & Tools','Piece','Physical','18'],
                ['Electrical Cable 2.5mm 100m','Hardware & Tools','Roll','Physical','18'],
                ['Switch Socket Double','Hardware & Tools','Piece','Physical','18'],
            ],
            'cosmetics' => [
                ['Body Lotion Cocoa 400ml','Cosmetics & Beauty','Bottle','Physical','18'],
                ['Body Oil Coconut 200ml','Cosmetics & Beauty','Bottle','Physical','18'],
                ['Petroleum Jelly Pure 250ml','Cosmetics & Beauty','Jar','Physical','18'],
                ['Face Cream Day 50g','Cosmetics & Beauty','Tube','Physical','18'],
                ['Sunscreen SPF50 100ml','Cosmetics & Beauty','Bottle','Physical','18'],
                ['Perfume EDP 50ml','Cosmetics & Beauty','Bottle','Physical','18'],
                ['Body Spray Fresh 150ml','Cosmetics & Beauty','Bottle','Physical','18'],
                ['Deodorant Roll-on 50ml','Cosmetics & Beauty','Piece','Physical','18'],
                ['Shampoo Repair 400ml','Cosmetics & Beauty','Bottle','Physical','18'],
                ['Conditioner Smooth 400ml','Cosmetics & Beauty','Bottle','Physical','18'],
                ['Hair Oil Argan 100ml','Cosmetics & Beauty','Bottle','Physical','18'],
                ['Hair Gel Strong 300ml','Cosmetics & Beauty','Jar','Physical','18'],
                ['Lipstick Matte Red','Cosmetics & Beauty','Piece','Variable','18'],
                ['Nail Polish Nude','Cosmetics & Beauty','Bottle','Variable','18'],
                ['Eyeshadow Palette 12','Cosmetics & Beauty','Piece','Variable','18'],
                ['Foundation Liquid Sand','Cosmetics & Beauty','Bottle','Variable','18'],
                ['Mascara Volume','Cosmetics & Beauty','Piece','Physical','18'],
                ['Makeup Brush Set 7pc','Cosmetics & Beauty','Set','Physical','18'],
                ['Hair Dryer 1800W','Cosmetics & Beauty','Piece','Physical','18'],
                ['Hair Straightener Ceramic','Cosmetics & Beauty','Piece','Physical','18'],
            ],
            'beverage' => [
                ['Water 1.5L','Beverages','Bottle','Physical','18'],
                ['Water 5L','Beverages','Bottle','Physical','18'],
                ['Soda Cola 300ml','Beverages','Bottle','Physical','18'],
                ['Soda Orange 300ml','Beverages','Bottle','Physical','18'],
                ['Soda Lemon 500ml','Beverages','Bottle','Physical','18'],
                ['Energy Drink 250ml','Beverages','Can','Physical','18'],
                ['Energy Drink 500ml','Beverages','Can','Physical','18'],
                ['Juice Orange 300ml','Beverages','Bottle','Physical','18'],
                ['Juice Mango 500ml','Beverages','Bottle','Physical','18'],
                ['Yoghurt Drink 500ml','Dairy','Bottle','Physical','0'],
                ['Milk Flavoured 500ml','Dairy','Bottle','Physical','0'],
                ['Water Dispenser 20L','Beverages','Bottle','Physical','18'],
                ['Soda Glass 300ml','Beverages','Bottle','Physical','18'],
                ['Tonic Water 500ml','Beverages','Bottle','Physical','18'],
                ['Ginger Drink 500ml','Beverages','Bottle','Physical','18'],
                ['Coconut Water 330ml','Beverages','Can','Physical','18'],
                ['Iced Tea Lemon 500ml','Beverages','Bottle','Physical','18'],
                ['Milk Shake 300ml','Dairy','Bottle','Physical','0'],
                ['Yoghurt Plain 500g','Dairy','Tub','Physical','0'],
                ['Cheese Spread 200g','Dairy','Jar','Physical','0'],
            ],
            'butchery' => [
                ['Beef Steak 1kg','Meat & Seafood','Kg','Weighted','18'],
                ['Beef Mince 1kg','Meat & Seafood','Kg','Weighted','18'],
                ['Goat Ribs 1kg','Meat & Seafood','Kg','Weighted','18'],
                ['Chicken Whole 1.2kg','Meat & Seafood','Piece','Weighted','18'],
                ['Chicken Breast 1kg','Meat & Seafood','Kg','Weighted','18'],
                ['Chicken Thighs 1kg','Meat & Seafood','Kg','Weighted','18'],
                ['Pork Chops 1kg','Meat & Seafood','Kg','Weighted','18'],
                ['Liver Beef 500g','Meat & Seafood','Kg','Weighted','18'],
                ['Kidney 500g','Meat & Seafood','Kg','Weighted','18'],
                ['Tripe Cleaned 1kg','Meat & Seafood','Kg','Weighted','18'],
                ['Sausage Beef 500g','Meat & Seafood','Pack','Weighted','18'],
                ['Sausage Chicken 500g','Meat & Seafood','Pack','Weighted','18'],
                ['Burger Patties 400g','Meat & Seafood','Pack','Weighted','18'],
                ['Fish Tilapia Whole 1kg','Meat & Seafood','Kg','Weighted','18'],
                ['Fish Nile Perch Fillet 1kg','Meat & Seafood','Kg','Weighted','18'],
                ['Prawns 500g','Meat & Seafood','Pack','Weighted','18'],
                ['Beef Samosa 6pc','Meat & Seafood','Pack','Weighted','18'],
                ['Meat Skewers 4pc','Meat & Seafood','Pack','Weighted','18'],
                ['Beef Soup Bones 1kg','Meat & Seafood','Kg','Weighted','18'],
                ['Oxtail 1kg','Meat & Seafood','Kg','Weighted','18'],
            ],
            'grocery' => [
                ['Tomato Round 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Onion Red 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Potato Irish 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Cabbage Head','Fruits & Vegetables','Piece','Physical','0'],
                ['Carrot 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Cucumber 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Spinach Bundle','Fruits & Vegetables','Bundle','Physical','0'],
                ['Kale Sukuma Bundle','Fruits & Vegetables','Bundle','Physical','0'],
                ['Banana Ripe Bunch','Fruits & Vegetables','Bunch','Physical','0'],
                ['Mango Alfonso 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Apple Fuji 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Avocado Hass 1kg','Fruits & Vegetables','Kg','Weighted','0'],
                ['Watermelon Whole','Fruits & Vegetables','Piece','Weighted','0'],
                ['Pineapple Whole','Fruits & Vegetables','Piece','Weighted','0'],
                ['Green Pepper 500g','Fruits & Vegetables','Kg','Weighted','0'],
                ['Garlic 250g','Fruits & Vegetables','Pack','Weighted','0'],
                ['Ginger Fresh 250g','Fruits & Vegetables','Pack','Weighted','0'],
                ['Lemon 500g','Fruits & Vegetables','Kg','Weighted','0'],
                ['Dhania Bundle','Fruits & Vegetables','Bundle','Physical','0'],
                ['Hoho Red 500g','Fruits & Vegetables','Kg','Weighted','0'],
            ],
            'bakery' => [
                ['White Bread Loaf','Bakery','Piece','Physical','18'],
                ['Brown Bread Loaf','Bakery','Piece','Physical','18'],
                ['Wholemeal Bread','Bakery','Piece','Physical','18'],
                ['Buns White 4pc','Bakery','Pack','Physical','18'],
                ['Buns Brown 4pc','Bakery','Pack','Physical','18'],
                ['Doughnut Sugar','Bakery','Piece','Physical','18'],
                ['Doughnut Chocolate','Bakery','Piece','Physical','18'],
                ['Cupcake Vanilla','Bakery','Piece','Physical','18'],
                ['Cupcake Chocolate','Bakery','Piece','Physical','18'],
                ['Birthday Cake 1kg Vanilla','Bakery','Piece','Physical','18'],
                ['Birthday Cake 1kg Chocolate','Bakery','Piece','Physical','18'],
                ['Meat Pie Chicken','Bakery','Piece','Physical','18'],
                ['Samosa Beef 3pc','Bakery','Pack','Physical','18'],
                ['Samosa Veg 3pc','Bakery','Pack','Physical','18'],
                ['Cookies Chocolate Chip 200g','Bakery','Packet','Physical','18'],
                ['Croissant Butter','Bakery','Piece','Physical','18'],
                ['Croissant Chocolate','Bakery','Piece','Physical','18'],
                ['Baguette French','Bakery','Piece','Physical','18'],
                ['Chapati Pack 5pc','Bakery','Pack','Physical','18'],
                ['Mandazi 4pc','Bakery','Pack','Physical','18'],
            ],
            'restaurant' => [
                ['Pilau Kuku Plate','Restaurant Supplies','Plate','Service','18'],
                ['Pilau Mbuzi Plate','Restaurant Supplies','Plate','Service','18'],
                ['Biriyani Chicken Plate','Restaurant Supplies','Plate','Service','18'],
                ['Chips Kavu Plate','Restaurant Supplies','Plate','Service','18'],
                ['Chips Masala Plate','Restaurant Supplies','Plate','Service','18'],
                ['Mishkaki Beef 250g','Restaurant Supplies','Plate','Service','18'],
                ['Mishkaki Chicken 250g','Restaurant Supplies','Plate','Service','18'],
                ['Grilled Fish Whole','Restaurant Supplies','Plate','Service','18'],
                ['Chicken Curry Plate','Restaurant Supplies','Plate','Service','18'],
                ['Beef Curry Plate','Restaurant Supplies','Plate','Service','18'],
                ['Vegetable Curry Plate','Restaurant Supplies','Plate','Service','18'],
                ['Burger Classic','Restaurant Supplies','Piece','Service','18'],
                ['Burger Double Cheese','Restaurant Supplies','Piece','Service','18'],
                ['Pizza Margherita Medium','Restaurant Supplies','Piece','Service','18'],
                ['Pizza Pepperoni Medium','Restaurant Supplies','Piece','Service','18'],
                ['Pasta Bolognese','Restaurant Supplies','Plate','Service','18'],
                ['Pasta Carbonara','Restaurant Supplies','Plate','Service','18'],
                ['Soup Chicken','Restaurant Supplies','Cup','Service','18'],
                ['Salad Greek','Restaurant Supplies','Plate','Service','18'],
                ['Soda 500ml Restaurant','Beverages','Bottle','Service','18'],
            ],
            'cafe' => [
                ['Espresso Single','Beverages','Cup','Service','18'],
                ['Espresso Double','Beverages','Cup','Service','18'],
                ['Cappuccino Regular','Beverages','Cup','Service','18'],
                ['Cappuccino Large','Beverages','Cup','Service','18'],
                ['Latte Vanilla','Beverages','Cup','Service','18'],
                ['Latte Caramel','Beverages','Cup','Service','18'],
                ['Americano Black','Beverages','Cup','Service','18'],
                ['Mocha Chocolate','Beverages','Cup','Service','18'],
                ['Tea Masala','Beverages','Cup','Service','18'],
                ['Tea Ginger','Beverages','Cup','Service','18'],
                ['Hot Chocolate','Beverages','Cup','Service','18'],
                ['Fresh Juice Passion 300ml','Beverages','Glass','Service','18'],
                ['Fresh Juice Mango 300ml','Beverages','Glass','Service','18'],
                ['Smoothie Banana','Beverages','Glass','Service','18'],
                ['Cake Slice Chocolate','Bakery','Piece','Service','18'],
                ['Cake Slice Red Velvet','Bakery','Piece','Service','18'],
                ['Sandwich Chicken','Bakery','Piece','Service','18'],
                ['Sandwich Tuna','Bakery','Piece','Service','18'],
                ['Croissant Almond','Bakery','Piece','Service','18'],
                ['Muffin Blueberry','Bakery','Piece','Service','18'],
            ],
            'hotel' => [
                ['Standard Single Room','Hotel Supplies','Night','Service','18'],
                ['Standard Double Room','Hotel Supplies','Night','Service','18'],
                ['Deluxe Single Room','Hotel Supplies','Night','Service','18'],
                ['Deluxe Double Room','Hotel Supplies','Night','Service','18'],
                ['Executive Suite','Hotel Supplies','Night','Service','18'],
                ['Family Room 4pax','Hotel Supplies','Night','Service','18'],
                ['Conference Hall Small','Hotel Supplies','Session','Service','18'],
                ['Conference Hall Large','Hotel Supplies','Session','Service','18'],
                ['Banquet Hall','Hotel Supplies','Session','Service','18'],
                ['Laundry Shirt','Hotel Supplies','Service','Service','18'],
                ['Laundry Trousers','Hotel Supplies','Service','Service','18'],
                ['Airport Pickup Sedan','Hotel Supplies','Trip','Service','18'],
                ['Airport Transfer Van','Hotel Supplies','Trip','Service','18'],
                ['Breakfast Buffet','Hotel Supplies','Plate','Service','18'],
                ['Lunch Buffet','Hotel Supplies','Plate','Service','18'],
                ['Dinner Buffet','Hotel Supplies','Plate','Service','18'],
                ['Swimming Pool Access','Hotel Supplies','Session','Service','18'],
                ['Gym Access Day','Hotel Supplies','Session','Service','18'],
                ['Spa Massage 60min','Hotel Supplies','Session','Service','18'],
                ['Minibar Soda','Beverages','Bottle','Service','18'],
            ],
            'agrovet' => [
                ['Maize Seeds Hybrid 2kg','Agrovet Supplies','Packet','Physical','0'],
                ['Bean Seeds Rosecoco 1kg','Agrovet Supplies','Packet','Physical','0'],
                ['Tomato Seeds Cal J 10g','Agrovet Supplies','Sachet','Physical','0'],
                ['Cabbage Seeds 10g','Agrovet Supplies','Sachet','Physical','0'],
                ['Broiler Starter 25kg','Agrovet Supplies','Bag','Physical','0'],
                ['Layer Mash 50kg','Agrovet Supplies','Bag','Physical','0'],
                ['Dairy Meal 25kg','Agrovet Supplies','Bag','Physical','0'],
                ['Mineral Block 5kg','Agrovet Supplies','Piece','Physical','0'],
                ['Dewormer Albendazole 100ml','Health & Pharmacy','Bottle','Physical','0'],
                ['Wound Spray 100ml Vet','Health & Pharmacy','Bottle','Physical','0'],
                ['Tick Spray 100ml','Health & Pharmacy','Bottle','Physical','0'],
                ['Mastitis Treatment','Health & Pharmacy','Tube','Physical','0'],
                ['Poultry Vitamin 100g','Agrovet Supplies','Packet','Physical','0'],
                ['Calcium Supplement 1L','Agrovet Supplies','Bottle','Physical','0'],
                ['Poultry Drinker 5L','General Merchandise','Piece','Physical','18'],
                ['Chicken Feeder 5kg','General Merchandise','Piece','Physical','18'],
                ['Ear Tag Yellow','General Merchandise','Piece','Physical','18'],
                ['Cattle Rope 10m','General Merchandise','Roll','Physical','18'],
                ['Sprayer Knapsack 16L','General Merchandise','Piece','Physical','18'],
                ['Gumboots Size 42','General Merchandise','Pair','Physical','18'],
            ],
            'agricultural' => [
                ['Urea 50kg','Agricultural Supplies','Bag','Physical','0'],
                ['DAP 50kg','Agricultural Supplies','Bag','Physical','0'],
                ['NPK 17-17-17 50kg','Agricultural Supplies','Bag','Physical','0'],
                ['CAN 50kg','Agricultural Supplies','Bag','Physical','0'],
                ['TSP 50kg','Agricultural Supplies','Bag','Physical','0'],
                ['MOP 50kg','Agricultural Supplies','Bag','Physical','0'],
                ['Compost Organic 25kg','Agricultural Supplies','Bag','Physical','0'],
                ['Foliar Feed 500ml','Agricultural Supplies','Bottle','Physical','0'],
                ['Herbicide Glyphosate 500ml','Agricultural Supplies','Bottle','Physical','0'],
                ['Insecticide Karate 100ml','Agricultural Supplies','Bottle','Physical','0'],
                ['Fungicide Mancozeb 500g','Agricultural Supplies','Packet','Physical','0'],
                ['Maize Seed SC719 5kg','Agrovet Supplies','Packet','Physical','0'],
                ['Jembe Hoe','General Merchandise','Piece','Physical','18'],
                ['Panga Standard','General Merchandise','Piece','Physical','18'],
                ['Wheelbarrow Metal','General Merchandise','Piece','Physical','18'],
                ['Watering Can 10L','General Merchandise','Piece','Physical','18'],
                ['Sprayer Pump 16L','General Merchandise','Piece','Physical','18'],
                ['Irrigation Pipe 1" 3m','General Merchandise','Piece','Physical','18'],
                ['Sprinkler Head Brass','General Merchandise','Piece','Physical','18'],
                ['Beehive Complete','General Merchandise','Piece','Physical','18'],
            ],
            'building_materials' => [
                ['Cement Bamburi 50kg','Building Materials','Bag','Physical','18'],
                ['Cement Dangote 50kg','Building Materials','Bag','Physical','18'],
                ['Iron Sheet IT5 3m','Building Materials','Piece','Physical','18'],
                ['Iron Sheet Versatile 3m','Building Materials','Piece','Physical','18'],
                ['Timber 2x4 3m','Building Materials','Piece','Physical','18'],
                ['Plywood 4x8 12mm','Building Materials','Sheet','Physical','18'],
                ['Nails 3" 5kg','Building Materials','Kg','Physical','18'],
                ['Steel Bar Y12','Building Materials','Piece','Physical','18'],
                ['Steel Bar Y16','Building Materials','Piece','Physical','18'],
                ['Door Steel Single','Building Materials','Piece','Physical','18'],
                ['Door Wood Mahogany','Building Materials','Piece','Physical','18'],
                ['Window Aluminium 90x120','Building Materials','Piece','Physical','18'],
                ['Paint Emulsion White 20L','Building Materials','Bucket','Physical','18'],
                ['Paint Weather Guard 20L','Building Materials','Bucket','Physical','18'],
                ['Primer White 4L','Building Materials','Tin','Physical','18'],
                ['Thinner 1L','Building Materials','Bottle','Physical','18'],
                ['Brush 4"','Building Materials','Piece','Physical','18'],
                ['Roller 9"','Building Materials','Piece','Physical','18'],
                ['Sandpaper Sheet','Building Materials','Sheet','Physical','18'],
                ['Gypsum Board 9mm','Building Materials','Piece','Physical','18'],
            ],
            'auto_parts' => [
                ['Engine Oil 5W30 4L','Auto Parts','Bottle','Physical','18'],
                ['Engine Oil 20W50 5L','Auto Parts','Bottle','Physical','18'],
                ['Oil Filter Toyota','Auto Parts','Piece','Physical','18'],
                ['Air Filter Toyota','Auto Parts','Piece','Physical','18'],
                ['Fuel Filter Diesel','Auto Parts','Piece','Physical','18'],
                ['Brake Pads Front Toyota','Auto Parts','Set','Physical','18'],
                ['Brake Disc Front','Auto Parts','Piece','Physical','18'],
                ['Brake Fluid DOT4 500ml','Auto Parts','Bottle','Physical','18'],
                ['Battery 12V 70Ah','Auto Parts','Piece','Physical','18'],
                ['Spark Plug NGK 4pc','Auto Parts','Set','Physical','18'],
                ['Wiper Blade 18"','Auto Parts','Piece','Physical','18'],
                ['Fan Belt','Auto Parts','Piece','Physical','18'],
                ['Timing Belt','Auto Parts','Piece','Physical','18'],
                ['Clutch Kit','Auto Parts','Set','Physical','18'],
                ['Shock Absorber Front','Auto Parts','Piece','Physical','18'],
                ['Tie Rod End','Auto Parts','Piece','Physical','18'],
                ['Ball Joint','Auto Parts','Piece','Physical','18'],
                ['Headlight Bulb H4','Auto Parts','Piece','Physical','18'],
                ['Tail Light Assembly','Auto Parts','Piece','Physical','18'],
                ['Radiator Coolant 1L','Auto Parts','Bottle','Physical','18'],
            ],
            'tyre' => [
                ['Tyre 155/70R13','Tyres & Batteries','Piece','Variable','18'],
                ['Tyre 185/65R14','Tyres & Batteries','Piece','Variable','18'],
                ['Tyre 195/65R15','Tyres & Batteries','Piece','Variable','18'],
                ['Tyre 205/55R16','Tyres & Batteries','Piece','Variable','18'],
                ['Tyre 265/65R17 SUV','Tyres & Batteries','Piece','Variable','18'],
                ['Tyre 11R22.5 Truck','Tyres & Batteries','Piece','Variable','18'],
                ['Tube 13"','Tyres & Batteries','Piece','Physical','18'],
                ['Tube 14"','Tyres & Batteries','Piece','Physical','18'],
                ['Rim Steel 13"','Tyres & Batteries','Piece','Physical','18'],
                ['Rim Alloy 15"','Tyres & Batteries','Piece','Physical','18'],
                ['Wheel Nut M12','Tyres & Batteries','Piece','Physical','18'],
                ['Wheel Nut M14','Tyres & Batteries','Piece','Physical','18'],
                ['Tyre Sealant 500ml','Tyres & Batteries','Bottle','Physical','18'],
                ['Tyre Inflator 12V','Tyres & Batteries','Piece','Physical','18'],
                ['Jack Hydraulic 2T','Tyres & Batteries','Piece','Physical','18'],
                ['Wheel Spanner','Tyres & Batteries','Piece','Physical','18'],
                ['Tyre Pressure Gauge','Tyres & Batteries','Piece','Physical','18'],
                ['Valve Cap Set','Tyres & Batteries','Pack','Physical','18'],
                ['Repair Kit Tubeless','Tyres & Batteries','Set','Physical','18'],
                ['Battery 12V 45Ah','Tyres & Batteries','Piece','Physical','18'],
            ],
            'fuel' => [
                ['Petrol Super 1L','Fuel & Lubricants','Litre','Physical','0'],
                ['Petrol Super 5L','Fuel & Lubricants','Bottle','Physical','0'],
                ['Diesel 1L','Fuel & Lubricants','Litre','Physical','0'],
                ['Diesel 5L','Fuel & Lubricants','Bottle','Physical','0'],
                ['Kerosene 1L','Fuel & Lubricants','Litre','Physical','0'],
                ['Engine Oil 1L','Fuel & Lubricants','Bottle','Physical','18'],
                ['Gear Oil 1L','Fuel & Lubricants','Bottle','Physical','18'],
                ['ATF 1L','Fuel & Lubricants','Bottle','Physical','18'],
                ['Brake Fluid 500ml','Fuel & Lubricants','Bottle','Physical','18'],
                ['Coolant 1L','Fuel & Lubricants','Bottle','Physical','18'],
                ['Grease 500g','Fuel & Lubricants','Tin','Physical','18'],
                ['Hydraulic Oil 5L','Fuel & Lubricants','Bottle','Physical','18'],
                ['2T Oil 500ml','Fuel & Lubricants','Bottle','Physical','18'],
                ['Diesel Additive 300ml','Fuel & Lubricants','Bottle','Physical','18'],
                ['Fuel Filter Universal','Fuel & Lubricants','Piece','Physical','18'],
                ['Air Freshener Car','Fuel & Lubricants','Piece','Physical','18'],
                ['Car Wash Shampoo 500ml','Fuel & Lubricants','Bottle','Physical','18'],
                ['Tyre Shine 500ml','Fuel & Lubricants','Bottle','Physical','18'],
                ['Car Vacuum 12V','Fuel & Lubricants','Piece','Physical','18'],
                ['Jumper Cables','Fuel & Lubricants','Set','Physical','18'],
            ],
            'bookshop' => [
                ['Mathematics Form 1 Textbook','Books & Printing','Piece','Physical','18'],
                ['Mathematics Form 2 Textbook','Books & Printing','Piece','Physical','18'],
                ['English Form 1 Textbook','Books & Printing','Piece','Physical','18'],
                ['Biology Form 1 Textbook','Books & Printing','Piece','Physical','18'],
                ['Chemistry Form 1 Textbook','Books & Printing','Piece','Physical','18'],
                ['Physics Form 1 Textbook','Books & Printing','Piece','Physical','18'],
                ['Swahili Kamusi','Books & Printing','Piece','Physical','18'],
                ['English Dictionary','Books & Printing','Piece','Physical','18'],
                ['Novel - Passed Like Shadows','Books & Printing','Piece','Physical','18'],
                ['Novel - Unanswered Cries','Books & Printing','Piece','Physical','18'],
                ['Exercise Book 32pg','Books & Printing','Piece','Physical','18'],
                ['Exercise Book 48pg','Books & Printing','Piece','Physical','18'],
                ['Exercise Book 96pg','Books & Printing','Piece','Physical','18'],
                ['Counter Book 2 Quire','Books & Printing','Piece','Physical','18'],
                ['Notebook Hardcover 200pg','Books & Printing','Piece','Physical','18'],
                ['Graph Book A4','Books & Printing','Piece','Physical','18'],
                ['Manila Envelope A4 Pack','Books & Printing','Pack','Physical','18'],
                ['Printing A4 Black','Books & Printing','Service','Service','18'],
                ['Photocopy A4','Books & Printing','Service','Service','18'],
                ['Lamination A4','Books & Printing','Service','Service','18'],
            ],
            'stationery' => [
                ['Ball Pen Blue','Stationery','Piece','Physical','18'],
                ['Ball Pen Black 10pk','Stationery','Pack','Physical','18'],
                ['Pencil HB','Stationery','Piece','Physical','18'],
                ['Pencil 2B 12pk','Stationery','Pack','Physical','18'],
                ['Eraser White','Stationery','Piece','Physical','18'],
                ['Sharpener Metal','Stationery','Piece','Physical','18'],
                ['Ruler 30cm','Stationery','Piece','Physical','18'],
                ['Ruler 15cm','Stationery','Piece','Physical','18'],
                ['A4 Paper 500 sheets Ream','Stationery','Ream','Physical','18'],
                ['A4 Paper Box 5 Reams','Stationery','Box','Physical','18'],
                ['File Box File','Stationery','Piece','Physical','18'],
                ['Spring File','Stationery','Piece','Physical','18'],
                ['Stapler Medium','Stationery','Piece','Physical','18'],
                ['Staples 24/6 1000pc','Stationery','Box','Physical','18'],
                ['Paper Clips Box','Stationery','Box','Physical','18'],
                ['Highlighter Yellow','Stationery','Piece','Physical','18'],
                ['Marker Black','Stationery','Piece','Physical','18'],
                ['Glue Stick 20g','Stationery','Piece','Physical','18'],
                ['Scissors Office 21cm','Stationery','Piece','Physical','18'],
                ['Calculator Scientific','Stationery','Piece','Physical','18'],
            ],
            'furniture' => [
                ['Office Chair Mesh','Furniture','Piece','Physical','18'],
                ['Office Chair Executive Leather','Furniture','Piece','Physical','18'],
                ['Office Desk 120x60','Furniture','Piece','Physical','18'],
                ['Office Desk L-shape','Furniture','Piece','Physical','18'],
                ['Dining Table 6-Seater','Furniture','Piece','Physical','18'],
                ['Dining Chairs Set 4','Furniture','Set','Physical','18'],
                ['Bed 4x6','Furniture','Piece','Physical','18'],
                ['Bed 5x6','Furniture','Piece','Physical','18'],
                ['Bed 6x6','Furniture','Piece','Physical','18'],
                ['Mattress 4x6 6"','Furniture','Piece','Physical','18'],
                ['Mattress 5x6 8"','Furniture','Piece','Physical','18'],
                ['Wardrobe 3-Door','Furniture','Piece','Physical','18'],
                ['Wardrobe Sliding 2-Door','Furniture','Piece','Physical','18'],
                ['Sofa 3-Seater Fabric','Furniture','Piece','Physical','18'],
                ['Sofa 2-Seater','Furniture','Piece','Physical','18'],
                ['Coffee Table Glass','Furniture','Piece','Physical','18'],
                ['TV Stand 48"','Furniture','Piece','Physical','18'],
                ['Bookshelf 4-tier','Furniture','Piece','Physical','18'],
                ['Cabinet Filing Metal','Furniture','Piece','Physical','18'],
                ['Shoe Rack 3-tier','Furniture','Piece','Physical','18'],
            ],
            'wholesale' => [
                ['Sugar 50kg Sack','Groceries','Sack','Physical','0'],
                ['Rice 25kg Sack','Groceries','Sack','Physical','0'],
                ['Wheat Flour 25kg Sack','Groceries','Sack','Physical','0'],
                ['Cooking Oil 20L Jerrycan','Cooking Essentials','Bottle','Physical','18'],
                ['Soda Carton 12x500ml','Beverages','Carton','Physical','18'],
                ['Water Carton 12x500ml','Beverages','Carton','Physical','18'],
                ['Biscuits Carton 24pk','Snacks & Confectionery','Carton','Physical','18'],
                ['Soap Carton 24 Bars','Personal Care','Carton','Physical','18'],
                ['Detergent Carton 12x1kg','Household & Cleaning','Carton','Physical','18'],
                ['Toilet Paper Carton 48 Rolls','Household & Cleaning','Carton','Physical','18'],
                ['Milk Carton 12x500ml','Dairy','Carton','Physical','0'],
                ['Juice Carton 12x500ml','Beverages','Carton','Physical','18'],
                ['Battery Carton AA 144pc','General Merchandise','Carton','Physical','18'],
                ['Matches Carton 100 Boxes','General Merchandise','Carton','Physical','18'],
                ['Candle Carton 50 Packs','General Merchandise','Carton','Physical','18'],
                ['Flour Sack 50kg','Groceries','Sack','Physical','0'],
                ['Beans Sack 50kg','Groceries','Sack','Physical','0'],
                ['Salt Sack 25kg','Groceries','Sack','Physical','0'],
                ['Tea Leaves Sack 10kg','Beverages','Sack','Physical','18'],
                ['Coffee Sack 10kg','Beverages','Sack','Physical','18'],
            ],
            'flower_gift' => [
                ['Rose Red Single','General Merchandise','Piece','Physical','18'],
                ['Rose Bouquet 12','General Merchandise','Bundle','Physical','18'],
                ['Mixed Bouquet Medium','General Merchandise','Bundle','Physical','18'],
                ['Orchid Pot','General Merchandise','Piece','Physical','18'],
                ['Gift Box Small','General Merchandise','Piece','Physical','18'],
                ['Gift Box Large','General Merchandise','Piece','Physical','18'],
                ['Greeting Card Birthday','Stationery','Piece','Physical','18'],
                ['Greeting Card Love','Stationery','Piece','Physical','18'],
                ['Teddy Bear Small 20cm','General Merchandise','Piece','Physical','18'],
                ['Teddy Bear Large 60cm','General Merchandise','Piece','Physical','18'],
                ['Photo Frame 8x10','General Merchandise','Piece','Physical','18'],
                ['Photo Frame A4','General Merchandise','Piece','Physical','18'],
                ['Balloon Helium','General Merchandise','Piece','Physical','18'],
                ['Ribbon Roll','General Merchandise','Roll','Physical','18'],
                ['Wrapping Paper Roll','General Merchandise','Roll','Physical','18'],
                ['Gift Bag Medium','General Merchandise','Piece','Physical','18'],
                ['Chocolate Box Heart','Snacks & Confectionery','Box','Physical','18'],
                ['Perfume Gift Set','Personal Care','Set','Physical','18'],
                ['Watch Gift Box','General Merchandise','Piece','Physical','18'],
                ['Vase Ceramic','General Merchandise','Piece','Physical','18'],
            ],
            'pet' => [
                ['Dog Food Dry 1kg','General Merchandise','Kg','Physical','18'],
                ['Dog Food Dry 5kg','General Merchandise','Bag','Physical','18'],
                ['Dog Food Wet 400g Tin','General Merchandise','Tin','Physical','18'],
                ['Cat Food Dry 1kg','General Merchandise','Kg','Physical','18'],
                ['Cat Food Wet 400g','General Merchandise','Tin','Physical','18'],
                ['Fish Food Flakes 100g','General Merchandise','Packet','Physical','18'],
                ['Bird Seed Mix 1kg','General Merchandise','Packet','Physical','18'],
                ['Dog Shampoo 500ml','Personal Care','Bottle','Physical','18'],
                ['Pet Shampoo Flea 500ml','Personal Care','Bottle','Physical','18'],
                ['Pet Collar Small','General Merchandise','Piece','Physical','18'],
                ['Pet Collar Medium','General Merchandise','Piece','Physical','18'],
                ['Pet Collar Large','General Merchandise','Piece','Physical','18'],
                ['Pet Leash Nylon 1.5m','General Merchandise','Piece','Physical','18'],
                ['Pet Cage Medium','General Merchandise','Piece','Physical','18'],
                ['Cat Litter 5kg','General Merchandise','Bag','Physical','18'],
                ['Dog Bed Medium','General Merchandise','Piece','Physical','18'],
                ['Pet Carrier Bag','General Merchandise','Piece','Physical','18'],
                ['Fish Tank 40L','General Merchandise','Piece','Physical','18'],
                ['Bird Cage Medium','General Merchandise','Piece','Physical','18'],
                ['Pet Toy Ball','General Merchandise','Piece','Physical','18'],
            ],
            'gaming' => [
                ['PlayStation 5 Console','Electronics','Piece','Physical','18'],
                ['PlayStation 5 Controller','Electronics','Piece','Physical','18'],
                ['Xbox Series X','Electronics','Piece','Physical','18'],
                ['Xbox Controller','Electronics','Piece','Physical','18'],
                ['Nintendo Switch','Electronics','Piece','Physical','18'],
                ['Game Controller Wireless','Electronics','Piece','Physical','18'],
                ['Gaming Headset RGB','Electronics','Piece','Physical','18'],
                ['Gaming Keyboard Mechanical','Electronics','Piece','Physical','18'],
                ['Gaming Mouse 3200dpi','Electronics','Piece','Physical','18'],
                ['Gaming Chair Racing','Furniture','Piece','Physical','18'],
                ['Gaming Desk 120cm','Furniture','Piece','Physical','18'],
                ['Game FIFA 2024 PS5','Electronics','Piece','Physical','18'],
                ['Game Call of Duty PS5','Electronics','Piece','Physical','18'],
                ['Game GTA V PS5','Electronics','Piece','Physical','18'],
                ['VR Headset','Electronics','Piece','Physical','18'],
                ['Streaming Mic USB','Electronics','Piece','Physical','18'],
                ['Webcam Gaming 1080p','Electronics','Piece','Physical','18'],
                ['Mousepad XL','Electronics','Piece','Physical','18'],
                ['Console Stand','Electronics','Piece','Physical','18'],
                ['Charging Dock PS5','Electronics','Piece','Physical','18'],
            ],
            'camera' => [
                ['DSLR Canon 250D','Electronics','Piece','Physical','18'],
                ['Mirrorless Sony A6400','Electronics','Piece','Physical','18'],
                ['Lens 50mm f/1.8','Electronics','Piece','Physical','18'],
                ['Lens 70-200mm f/2.8','Electronics','Piece','Physical','18'],
                ['Camera Bag Lowepro','Electronics','Piece','Physical','18'],
                ['Tripod Aluminium 160cm','Electronics','Piece','Physical','18'],
                ['Gimbal Stabilizer','Electronics','Piece','Physical','18'],
                ['Memory Card 64GB SD','Electronics','Piece','Physical','18'],
                ['Memory Card 128GB SD','Electronics','Piece','Physical','18'],
                ['Camera Battery LP-E10','Electronics','Piece','Physical','18'],
                ['Battery Charger Dual','Electronics','Piece','Physical','18'],
                ['Flash Speedlite','Electronics','Piece','Physical','18'],
                ['Studio Light Kit','Electronics','Piece','Physical','18'],
                ['Reflector 5-in-1','Electronics','Piece','Physical','18'],
                ['Lens Cleaning Kit','Electronics','Set','Physical','18'],
                ['Action Camera 4K','Electronics','Piece','Physical','18'],
                ['Drone 4K','Electronics','Piece','Physical','18'],
                ['Photo Printer Mini','Electronics','Piece','Physical','18'],
                ['Ink Cartridge Photo','Electronics','Piece','Physical','18'],
                ['Photo Paper Glossy 50 sheets','Stationery','Pack','Physical','18'],
            ],
            'jewelry' => [
                ['Ring Gold 18K','General Merchandise','Piece','Variable','18'],
                ['Ring Silver 925','General Merchandise','Piece','Variable','18'],
                ['Necklace Gold Chain 45cm','General Merchandise','Piece','Variable','18'],
                ['Necklace Silver Chain','General Merchandise','Piece','Variable','18'],
                ['Bracelet Gold','General Merchandise','Piece','Variable','18'],
                ['Bracelet Beaded','General Merchandise','Piece','Variable','18'],
                ['Earrings Stud Gold','General Merchandise','Pair','Variable','18'],
                ['Earrings Hoop Silver','General Merchandise','Pair','Variable','18'],
                ['Pendant Heart Gold','General Merchandise','Piece','Variable','18'],
                ['Chain Gold 60cm','General Merchandise','Piece','Variable','18'],
                ['Watch Men Leather','General Merchandise','Piece','Physical','18'],
                ['Watch Women Rose Gold','General Merchandise','Piece','Physical','18'],
                ['Watch Smart Digital','Electronics','Piece','Physical','18'],
                ['Bangle Set 6pc','General Merchandise','Set','Variable','18'],
                ['Anklet Silver','General Merchandise','Piece','Variable','18'],
                ['Brooch Vintage','General Merchandise','Piece','Variable','18'],
                ['Cufflinks Silver','General Merchandise','Pair','Variable','18'],
                ['Tiara Bridal','General Merchandise','Piece','Variable','18'],
                ['Jewelry Box Wooden','General Merchandise','Piece','Physical','18'],
                ['Cleaning Cloth Jewelry','General Merchandise','Piece','Physical','18'],
            ],
            'industrial' => [
                ['Welding Machine Inverter 200A','General Merchandise','Piece','Physical','18'],
                ['Welding Electrodes 3.2mm 5kg','General Merchandise','Box','Physical','18'],
                ['Safety Helmet White','General Merchandise','Piece','Physical','18'],
                ['Safety Boots Steel Toe 42','General Merchandise','Pair','Variable','18'],
                ['Safety Gloves Leather','General Merchandise','Pair','Physical','18'],
                ['Safety Goggles Clear','General Merchandise','Piece','Physical','18'],
                ['Drill Machine 13mm','General Merchandise','Piece','Physical','18'],
                ['Angle Grinder 115mm','General Merchandise','Piece','Physical','18'],
                ['Circular Saw 185mm','General Merchandise','Piece','Physical','18'],
                ['Air Compressor 50L','General Merchandise','Piece','Physical','18'],
                ['Water Pump 1HP','General Merchandise','Piece','Physical','18'],
                ['Generator 5KVA','General Merchandise','Piece','Physical','18'],
                ['Concrete Mixer 350L','General Merchandise','Piece','Physical','18'],
                ['Scaffolding Frame','General Merchandise','Piece','Physical','18'],
                ['Ladder Aluminium 6m','General Merchandise','Piece','Physical','18'],
                ['Wheelbarrow Heavy Duty','General Merchandise','Piece','Physical','18'],
                ['Shovel Square','General Merchandise','Piece','Physical','18'],
                ['Hammer Sledge 4kg','General Merchandise','Piece','Physical','18'],
                ['Tape Measure 10m','General Merchandise','Piece','Physical','18'],
                ['Tool Box Metal 5-tray','General Merchandise','Piece','Physical','18'],
            ],
            'cleaning' => [
                ['Laundry Detergent Powder 1kg','Household & Cleaning','Bag','Physical','18'],
                ['Laundry Detergent Liquid 1L','Household & Cleaning','Bottle','Physical','18'],
                ['Dishwashing Liquid 500ml','Household & Cleaning','Bottle','Physical','18'],
                ['Dishwashing Liquid 1L','Household & Cleaning','Bottle','Physical','18'],
                ['Bleach 500ml','Household & Cleaning','Bottle','Physical','18'],
                ['Bleach 1L','Household & Cleaning','Bottle','Physical','18'],
                ['Floor Cleaner 500ml','Household & Cleaning','Bottle','Physical','18'],
                ['Floor Cleaner 1L','Household & Cleaning','Bottle','Physical','18'],
                ['Toilet Cleaner 500ml','Household & Cleaning','Bottle','Physical','18'],
                ['Glass Cleaner 500ml','Household & Cleaning','Bottle','Physical','18'],
                ['Disinfectant 500ml','Household & Cleaning','Bottle','Physical','18'],
                ['Disinfectant 1L','Household & Cleaning','Bottle','Physical','18'],
                ['Hand Sanitizer 100ml','Personal Care','Bottle','Physical','18'],
                ['Hand Sanitizer 500ml','Personal Care','Bottle','Physical','18'],
                ['Broom Soft','Household & Cleaning','Piece','Physical','18'],
                ['Mop Stick','Household & Cleaning','Piece','Physical','18'],
                ['Mop Bucket with Wringer','Household & Cleaning','Piece','Physical','18'],
                ['Tissue Box 100 sheets','Household & Cleaning','Box','Physical','18'],
                ['Toilet Paper 10 Rolls','Household & Cleaning','Pack','Physical','18'],
                ['Trash Bags 30L Roll','Household & Cleaning','Roll','Physical','18'],
            ],
            'baby' => [
                ['Baby Diapers Newborn 20s','Baby Care','Pack','Variable','18'],
                ['Baby Diapers Medium 20s','Baby Care','Pack','Variable','18'],
                ['Baby Diapers Large 20s','Baby Care','Pack','Variable','18'],
                ['Baby Wipes 80s','Baby Care','Pack','Physical','18'],
                ['Baby Wipes 40s Travel','Baby Care','Pack','Physical','18'],
                ['Baby Lotion 200ml','Baby Care','Bottle','Physical','18'],
                ['Baby Oil 200ml','Baby Care','Bottle','Physical','18'],
                ['Baby Powder 200g','Baby Care','Tin','Physical','18'],
                ['Baby Shampoo 200ml','Baby Care','Bottle','Physical','18'],
                ['Baby Soap Bar','Baby Care','Piece','Physical','18'],
                ['Baby Clothes Set Newborn','Baby Care','Set','Variable','18'],
                ['Baby Romper 3-6M','Baby Care','Piece','Variable','18'],
                ['Baby Shoes Soft Sole','Baby Care','Pair','Variable','18'],
                ['Baby Bottle 250ml','Baby Care','Piece','Physical','18'],
                ['Baby Bottle Anti-Colic','Baby Care','Piece','Physical','18'],
                ['Pacifier Silicone','Baby Care','Piece','Physical','18'],
                ['Baby Blanket Fleece','Baby Care','Piece','Physical','18'],
                ['Baby Carrier Wrap','Baby Care','Piece','Physical','18'],
                ['Baby High Chair','Baby Care','Piece','Physical','18'],
                ['Baby Stroller','Baby Care','Piece','Physical','18'],
            ],
            'fitness' => [
                ['Dumbbell 5kg','General Merchandise','Piece','Variable','18'],
                ['Dumbbell 10kg','General Merchandise','Piece','Variable','18'],
                ['Barbell 20kg','General Merchandise','Piece','Physical','18'],
                ['Weight Plate 5kg','General Merchandise','Piece','Variable','18'],
                ['Weight Plate 10kg','General Merchandise','Piece','Variable','18'],
                ['Kettlebell 8kg','General Merchandise','Piece','Variable','18'],
                ['Kettlebell 16kg','General Merchandise','Piece','Variable','18'],
                ['Yoga Mat 6mm','General Merchandise','Piece','Physical','18'],
                ['Yoga Mat Premium 10mm','General Merchandise','Piece','Physical','18'],
                ['Resistance Band Set 5pc','General Merchandise','Set','Physical','18'],
                ['Skipping Rope Speed','General Merchandise','Piece','Physical','18'],
                ['Skipping Rope Weighted','General Merchandise','Piece','Physical','18'],
                ['Sports Shoes Men 42','General Merchandise','Pair','Variable','18'],
                ['Sports Shoes Women 38','General Merchandise','Pair','Variable','18'],
                ['Gym Gloves Medium','General Merchandise','Pair','Variable','18'],
                ['Shaker Bottle 700ml','General Merchandise','Piece','Physical','18'],
                ['Treadmill Electric','General Merchandise','Piece','Physical','18'],
                ['Exercise Bike Spinning','General Merchandise','Piece','Physical','18'],
                ['Bench Press Adjustable','General Merchandise','Piece','Physical','18'],
                ['Pull-up Bar Doorway','General Merchandise','Piece','Physical','18'],
            ],
            'paint' => [
                ['Emulsion Paint White 20L','General Merchandise','Bucket','Physical','18'],
                ['Emulsion Paint Cream 20L','General Merchandise','Bucket','Physical','18'],
                ['Weather Guard Paint White 20L','General Merchandise','Bucket','Physical','18'],
                ['Gloss Paint White 4L','General Merchandise','Tin','Physical','18'],
                ['Gloss Paint Blue 4L','General Merchandise','Tin','Physical','18'],
                ['Primer White 4L','General Merchandise','Tin','Physical','18'],
                ['Undercoat Grey 4L','General Merchandise','Tin','Physical','18'],
                ['Varnish Clear 1L','General Merchandise','Tin','Physical','18'],
                ['Paint Brush 2"','General Merchandise','Piece','Physical','18'],
                ['Paint Brush 4"','General Merchandise','Piece','Physical','18'],
                ['Roller 9" + Tray','General Merchandise','Set','Physical','18'],
                ['Roller Refill 9"','General Merchandise','Piece','Physical','18'],
                ['Sandpaper 120 Grit','General Merchandise','Sheet','Physical','18'],
                ['Sandpaper 240 Grit','General Merchandise','Sheet','Physical','18'],
                ['Thinner General Purpose 1L','General Merchandise','Bottle','Physical','18'],
                ['Thinner 5L','General Merchandise','Bottle','Physical','18'],
                ['Putty Filler 5kg','General Merchandise','Bag','Physical','18'],
                ['Masking Tape 1"','General Merchandise','Roll','Physical','18'],
                ['Drop Cloth 4x5m','General Merchandise','Piece','Physical','18'],
                ['Ladder Aluminium 3m','General Merchandise','Piece','Physical','18'],
            ],
            'laboratory' => [
                ['Microscope Binocular','General Merchandise','Piece','Physical','18'],
                ['Microscope Monocular Student','General Merchandise','Piece','Physical','18'],
                ['Centrifuge 6x15ml','General Merchandise','Piece','Physical','18'],
                ['Balance Digital 0.01g','General Merchandise','Piece','Physical','18'],
                ['Balance Analytical 0.001g','General Merchandise','Piece','Physical','18'],
                ['Test Tube 15ml Pack 100','General Merchandise','Pack','Physical','18'],
                ['Beaker 250ml Glass','General Merchandise','Piece','Physical','18'],
                ['Beaker 500ml Glass','General Merchandise','Piece','Physical','18'],
                ['Measuring Cylinder 100ml','General Merchandise','Piece','Physical','18'],
                ['Measuring Cylinder 500ml','General Merchandise','Piece','Physical','18'],
                ['Petri Dish 90mm Pack 20','General Merchandise','Pack','Physical','18'],
                ['Pipette Graduated 10ml','General Merchandise','Piece','Physical','18'],
                ['Pipette Micropipette 1000ul','General Merchandise','Piece','Physical','18'],
                ['Gloves Nitrile Medium Box 100','General Merchandise','Box','Physical','18'],
                ['Gloves Latex Large Box 100','General Merchandise','Box','Physical','18'],
                ['Lab Coat White Medium','General Merchandise','Piece','Variable','18'],
                ['Lab Coat White Large','General Merchandise','Piece','Variable','18'],
                ['Safety Goggles Clear','General Merchandise','Piece','Physical','18'],
                ['Bunsen Burner','General Merchandise','Piece','Physical','18'],
                ['Hot Plate Magnetic Stirrer','General Merchandise','Piece','Physical','18'],
            ],
        ];
    }
}
